In [3]:
!pip install boto3

Requirement already satisfied: boto3 in c:\programdata\anaconda3\lib\site-packages (1.16.47)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from boto3) (0.10.0)
Requirement already satisfied: botocore<1.20.0,>=1.19.47 in c:\programdata\anaconda3\lib\site-packages (from boto3) (1.19.47)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in c:\programdata\anaconda3\lib\site-packages (from boto3) (0.3.3)
Requirement already satisfied: urllib3<1.27,>=1.25.4; python_version != "3.4" in c:\programdata\anaconda3\lib\site-packages (from botocore<1.20.0,>=1.19.47->boto3) (1.25.11)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\programdata\anaconda3\lib\site-packages (from botocore<1.20.0,>=1.19.47->boto3) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.20.0,>=1.19.47->boto3) (1.15.0)

In [2]:
!python -m pip install --user --upgrade pip

Requirement already satisfied: pip in c:\users\naga raja paidimarri\appdata\roaming\python\python38\site-packages (20.3.3)

In [5]:
!pip install --user s3fs

Collecting s3fs
  Using cached s3fs-0.5.2-py3-none-any.whl (22 kB)
Requirement already satisfied: fsspec>=0.8.0 in c:\programdata\anaconda3\lib\site-packages (from s3fs) (0.8.3)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
boto3 1.16.47 requires botocore<1.20.0,>=1.19.47, but you have botocore 1.17.44 which is incompatible.

Collecting aiobotocore>=1.0.1
  Using cached aiobotocore-1.1.2-py3-none-any.whl (45 kB)
Requirement already satisfied: aioitertools>=0.5.1 in c:\programdata\anaconda3\lib\site-packages (from aiobotocore>=1.0.1->s3fs) (0.7.1)
Requirement already satisfied: aiohttp>=3.3.1 in c:\programdata\anaconda3\lib\site-packages (from aiobotocore>=1.0.1->s3fs) (3.7.3)
Requirement already satisfied: wrapt>=1.10.10 in c:\programdata\anaconda3\lib\site-packages (from aiobotocore>=1.0.1->s3fs) (1.11.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\programdata\anaconda3\lib\site-packages (from aiohttp>=3.3.1->aiobotocore>=1.0.1->s3fs) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\programdata\anaconda3\lib\site-packages (from aiohttp>=3.3.1->aiobotocore>=1.0.1->s3fs) (20.3.0)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\programdata\anaconda3\lib\site-packages (from aiohttp>=3.3.1->aiobotocore>=1.0.1->s3fs) (3.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\programdata\anaconda3\lib\site-packages (from aiohttp>=3.3.1->aiobotocore>=1.0.1->s3fs) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\programdata\anaconda3\lib\site-packages (from aiohttp>=3.3.1->aiobotocore>=1.0.1->s3fs) (3.7.4.3)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\programdata\anaconda3\lib\site-packages (from aiohttp>=3.3.1->aiobotocore>=1.0.1->s3fs) (5.1.0)
Collecting botocore<1.17.45,>=1.17.44
  Using cached botocore-1.17.44-py2.py3-none-any.whl (6.5 MB)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from botocore<1.17.45,>=1.17.44->aiobotocore>=1.0.1->s3fs) (0.10.0)
Requirement already satisfied: urllib3<1.26,>=1.20 in c:\programdata\anaconda3\lib\site-packages (from botocore<1.17.45,>=1.17.44->aiobotocore>=1.0.1->s3fs) (1.25.11)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\programdata\anaconda3\lib\site-packages (from botocore<1.17.45,>=1.17.44->aiobotocore>=1.0.1->s3fs) (2.8.1)
Collecting docutils<0.16,>=0.10
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.17.45,>=1.17.44->aiobotocore>=1.0.1->s3fs) (1.15.0)
Requirement already satisfied: idna>=2.0 in c:\programdata\anaconda3\lib\site-packages (from yarl<2.0,>=1.0->aiohttp>=3.3.1->aiobotocore>=1.0.1->s3fs) (2.10)
Installing collected packages: docutils, botocore, aiobotocore, s3fs
Successfully installed aiobotocore-1.1.2 botocore-1.17.44 docutils-0.15.2 s3fs-0.5.2

In [8]:
import s3fs
import pandas as pd
import numpy as np
from attributes import *
import boto3, os
import gc
import pickle
s3 = boto3.resource('s3')

In [5]:
! aws s3 ls

2020-12-21 19:41:16 amplify-myhomely-staging-04110-deployment
2020-12-30 17:01:58 cf-templates-zh58d9ea8rbl-us-west-2
2020-12-20 17:50:34 myhomely

In [7]:
file_to_read = open("datadictionary.pickle", "rb")
datadictionary = pickle.load(file_to_read)
print(datadictionary)

{'PP_TOT': 'Total - Age groups and average age of the population', 'PP_0_14': 'Population 0 to 14 years', 'PP_0_4': 'Population 0 to 4 years', 'PP_5_9': 'Population 5 to 9 years', 'PP_10_14': 'Population 10 to 14 years', 'PP_15_64': 'Population 15 to 64 years', 'PP_15_19': 'Population 15 to 19 years', 'PP_20_24': 'Population 20 to 24 years', 'PP_25_29': 'Population 25 to 29 years', 'PP_30_34': 'Population 30 to 34 years', 'PP_35_39': 'Population 35 to 39 years', 'PP_40_44': 'Population 40 to 44 years', 'PP_45_49': 'Population 45 to 49 years', 'PP_50_54': 'Population 50 to 54 years', 'PP_55_59': 'Population 55 to 59 years', 'PP_60_64': 'Population 60 to 64 years', 'PP_65_': 'Population 65 years and over', 'PP_65_69': 'Population 65 to 69 years', 'PP_70_74': 'Population 70 to 74 years', 'PP_75_79': 'Population 75 to 79 years', 'PP_80_84': 'Population 80 to 84 years', 'PP_85': 'Population 85 years and over', 'PP_85_89': 'Population 85 to 89 years', 'PP_90_94': 'Population 90 to 94 years', 'PP_95_99': 'Population 95 to 99 years', 'PP_100_': 'Population 100 years and over', 'PP_PP_AVG': 'Average age of total population', 'PP_FEMALE': 'Total - Age groups and average age of the population - Female', 'PP_FM0_14': 'Population 0 to 14 years-Female', 'PP_FM0_4': 'Population 0 to 4 years-Female', 'PP_FM5_9': 'Population 5 to 9 years-Female', 'PP_FM10_14': 'Population 10 to 14 years-Female', 'PP_FM15_64': 'Population 15 to 64 years-Female', 'PP_FM15_19': 'Population 15 to 19 years-Female', 'PP_FM20_24': 'Population 20 to 24 years-Female', 'PP_FM25_29': 'Population 25 to 29 years-Female', 'PP_FM30_34': 'Population 30 to 34 years-Female', 'PP_FM35_39': 'Population 35 to 39 years-Female', 'PP_FM40_44': 'Population 40 to 44 years-Female', 'PP_FM45_49': 'Population 45 to 49 years-Female', 'PP_FM50_54': 'Population 50 to 54 years-Female', 'PP_FM55_59': 'Population 55 to 59 years-Female', 'PP_FM60_64': 'Population 60 to 64 years-Female', 'PP_FM65_': 'Population 65 years and over-Female', 'PP_FM65_69': 'Population 65 to 69 years-Female', 'PP_FM70_74': 'Population 70 to 74 years-Female', 'PP_FM75_79': 'Population 75 to 79 years-Female', 'PP_FM80_84': 'Population 80 to 84 years-Female', 'PP_FM85': 'Population 85 years and over-Female', 'PP_FM85_89': 'Population 85 to 89 years-Female', 'PP_FM90_94': 'Population 90 to 94 years-Female', 'PP_FM95_99': 'Population 95 to 99 years-Female', 'PP_FM100_': 'Population 100 years and over-Female', 'PP_FM_AVG': 'Average age of female population', 'PP_MALE': 'Total - Age groups and average age of the population - Male', 'PP_M0_14': 'Population 0 to 14 years-Male', 'PP_M0_4': 'Population 0 to 4 years-Male', 'PP_M5_9': 'Population 5 to 9 years-Male', 'PP_M10_14': 'Population 10 to 14 years-Male', 'PP_M15_64': 'Population 15 to 64 years-Male', 'PP_M15_19': 'Population 15 to 19 years-Male', 'PP_M20_24': 'Population 20 to 24 years-Male', 'PP_M25_29': 'Population 25 to 29 years-Male', 'PP_M30_34': 'Population 30 to 34 years-Male', 'PP_M35_39': 'Population 35 to 39 years-Male', 'PP_M40_44': 'Population 40 to 44 years-Male', 'PP_M45_49': 'Population 45 to 49 years-Male', 'PP_M50_54': 'Population 50 to 54 years-Male', 'PP_M55_59': 'Population 55 to 59 years-Male', 'PP_M60_64': 'Population 60 to 64 years-Male', 'PP_M65_': 'Population 65 years and over-Male', 'PP_M65_69': 'Population 65 to 69 years-Male', 'PP_M70_74': 'Population 70 to 74 years-Male', 'PP_M75_79': 'Population 75 to 79 years-Male', 'PP_M80_84': 'Population 80 to 84 years-Male', 'PP_M85': 'Population 85 years and over-Male', 'PP_M85_89': 'Population 85 to 89 years-Male', 'PP_M90_94': 'Population 90 to 94 years-Male', 'PP_M95_99': 'Population 95 to 99 years-Male', 'PP_M100_': 'Population 100 years and over-Male', 'PP_M_AVG': 'Average age of male population', 'PP_POP15_': 'Total - Marital status for the population aged 15 years and over', 'PP_MR_CL': 'Population Married or living common law', 'PP_LMR': 'Population Married', 'PP_CL_Y': 'Population Living common law', 'PP_NMRCL': 'Population Not married and not living common law', 'PP_NMR': 'Population Never married', 'PP_SEP': 'Population Separated', 'PP_DIVORCE': 'Population Divorced', 'PP_WIDOW': 'Population Widowed', 'PP_PP_MED': 'Median age of total population', 'PP_FM_MED': 'Median age of female population', 'PP_M_MED': 'Median age of male population', 'FM_2P': 'Number of families with 2 persons', 'FM_3P': 'Number of families with 3 persons', 'FM_4P': 'Number of families with 4 persons', 'FM_5_P': 'Number of families with 5 or more persons', 'FM_AVG_P': 'Average number of persons per census family', 'FM_TOT_S': 'Total number of census families in private households', 'FM_CPNKID': 'Without children at home', 'FM_CPKIDS': 'With children at home', 'FM_CP1KID': '1 child', 'FM_CP2KID': '2 children', 'FM_CP3KID': '3 or more children', 'FM_MA': 'Married couples', 'FM_MANKID': 'Without children at home', 'FM_MAKIDS': 'With children at home', 'FM_MA1KID': '1 child', 'FM_MA2KID': '2 children', 'FM_MA3KID': '3 or more children', 'FM_CLNKID': 'Without children at home', 'FM_CLKIDS': 'With children at home', 'FM_CL1KID': '1 child', 'FM_CL2KID': '2 children', 'FM_CL3KID': '3 or more children', 'FM_LP': 'Total lone-parent families by sex of parent and number of children', 'FM_LP1KID': '1 child', 'FM_LP2KID': '2 children', 'FM_LP3KID': '3 or more children', 'FM_LF': 'Female parent', 'FM_LF1KID': '1 child', 'FM_LF2KID': '2 children', 'FM_LF3KID': '3 or more children', 'FM_LM': 'Male parent', 'FM_LM1KID': '1 child', 'FM_LM2KID': '2 children', 'FM_LM3KID': '3 or more children', 'FM_CH_6': 'Under six years of age', 'FM_CH614': '6 to 14 years', 'FM_CH1517': '15 to 17 years', 'FM_CH1824': '18 to 24 years', 'FM_CH25_': '25 years and over', 'FM_NF_P_R': 'Living with relatives, but non-relatives may be present.', 'FM_NF_P_N': 'Living with non-relatives only', 'FM_NF_P_A': 'Living alone', 'FM_P': 'Number of census family persons', 'FM_P65_': 'Total number of persons 65 years and over in private households', 'FM_NF_P65': 'Number of persons not in census families aged 65 years and over', 'FM_N_P65R': 'Living with relatives', 'FM_N_P65N': 'Living with non-relatives only', 'FM_N_P65A': 'Living alone', 'FM_FM_P65': 'Number of census family persons aged 65 years and over', 'FM_TOT': 'Total - Census families in private households', 'FM_CP': 'Total couple families by family structure and number of children', 'FM_CL': 'Common-law couples', 'FM_CH': 'Total number of children at home', 'FM_AVCH': 'Average number of children at home per census family', 'FM_PH_P': 'Total number of persons in private households by living arrangements', 'FM_NF_P': 'Number of non-family persons', 'HH_1P': 'Household 1 person', 'HH_2P': 'Household 2 persons', 'HH_3P': 'Household 3 persons', 'HH_4P': 'Household 4 persons', 'HH_5P': 'Household 5 or more persons', 'HH_NUMPINH': 'Number of persons in private households', 'HH_AVGPINH': 'Average number of persons in private households', 'HH_CP_NC': 'Household Without children in a census family', 'HH_CP_CH': 'Household With children in a census family', 'HH_NOFMHH1': 'One-person households', 'HH_NOFMHH2': 'Two-or-more person non-census-family households', 'HH_REOW_30': 'Household Spending less than 30% of total income on shelter costs', 'HH_REOW30': 'Household Spending 30% or more of total income on shelter costs', 'HH_REOW99': 'Spending 30% to less than 100% of household total income on shelter costs', 'HH_OWN': 'Total - Owner households in non-farm, non-reserve private dwellings', 'HH_PMORT': '% of owner households with a mortgage', 'HH_POWN30': '% of owner households spending 30% or more of its income on shelter costs', 'HH_RENT': 'Total - Tenant households in non-farm, non-reserve private dwellings', 'HH_PRENT': '% of tenant households in subsidized housing', 'HH_PRENT30': '% of tenant households spending 30% or more of its income on shelter costs', 'HH_MRENT': 'Household Median monthly shelter costs for rented dwellings ($)', 'HH_TOT': 'Total - Private households by household size', 'HH_TOTHH': 'Total - Private households by household type,', 'HH_ONEFMHH': 'One-family households', 'HH_MULFMHH': 'Multiple-family households', 'HH_NOFMHH': 'Non-family households', 'HH_TOT_A': 'Total -  Owner and tenant households with household total income greater than zero', 'HH_ARENT': 'Average monthly shelter costs for rented dwellings ($)', 'DW_TOT': 'Total - Occupied private dwellings by structural type of dwelling', 'DW_OT': 'Other attached dwelling', 'DW_TOTDWL5': 'Total - Private households by tenure', 'DW_OWNED': 'Owned: Some member of the household owns the dwelling.', 'DW_RENTED': 'Rented: Some member of the household rents the dwelling.', 'DW_BANDH': 'Band housing: Refers to the dwelling that is Band housing (on an Indian reserve or settlement).', 'DW_PTCON': 'Condominium', 'DW_NPTCON': 'Not condominium', 'DW_BRM0': 'No bedrooms', 'DW_BRM1': '1 bedroom', 'DW_BRM2': '2 bedrooms', 'DW_BRM3': '3 bedrooms', 'DW_BRM4_': '4 or more bedrooms', 'DW_TOTDWL3': 'Total - Occupied private dwellings by number of rooms', 'DW_RM_4': '1 to 4 rooms', 'DW_RM5': '5 rooms', 'DW_RM6': '6 rooms', 'DW_RM7': '7 rooms', 'DW_RM8_': '8 or more rooms', 'DW_TOTDWL9': 'Total - Private households by number of persons per room', 'DW_PPR_1': 'One person or fewer per room', 'DW_PPR2_': 'More than 1 person per room', 'DW_SUIT': 'Suitable', 'DW_NSUIT': 'Not suitable', 'DW_TOTDWL2': 'Total - Occupied private dwellings by period of construction', 'DW_CON_60': '1960 or before', 'DW_CON6180': '1961 to 1980', 'DW_CON8190': '1981 to 1990', 'DW_CON9100': '1991 to 2000', 'DW_CON0105': '2001 to 2005', 'DW_CON0610': '2006 to 2010', 'DW_CON1116': '2011 to 2016', 'DW_CON17_': '2017 and after', 'DW_MT1': '1 household maintainer', 'DW_MT2': '2 household maintainers', 'DW_MT3_': '3 or more household maintainers', 'DW_TOTDWL8': 'Total - Private households by age of primary household maintainers', 'DW_MT_25': '15 to 24 years', 'DW_MT2534': '25 to 34 years', 'DW_MT3544': '35 to 44 years', 'DW_MT4554': '45 to 54 years', 'DW_MT5564': '55 to 64 years', 'DW_MT6574': '65 to 74 years', 'DW_MT7584': '75 to 84 years', 'DW_MT85_': '85 years and over', 'DW_MCOST': 'Median monthly shelter costs for owned dwellings ($)', 'DW_MVALUE': 'Median value of dwellings ($)', 'DW_MINVAL': 'Minimum value of dwellings ($)', 'DW_MAXVAL': 'Maximum value of dwellings ($)', 'DW_VALSTD': 'Standard deviation (dispersion) of dwelling values in the postal code', 'DW_SINGLE': 'Single-detached house', 'DW_APT5_': 'Apartment, building that has five or more storeys', 'DW_SEMI': 'Semi-detached house', 'DW_ROW': 'Row house', 'DW_DUP': 'Apartment, detached duplex', 'DW_APT_5': 'Apartment, building that has fewer than five storeys', 'DW_OT_SING': 'Other single-attached house', 'DW_MOVA': 'Movable dwelling', 'DW_TOTDWL6': 'Total - Occupied private dwellings by condominium status', 'DW_TOTDWL4': 'Total - Occupied private dwellings by number of bedrooms', 'DW_ARMSPDW': 'Average number of rooms per dwelling', 'DW_TOTDWLA': 'Total - Private households by housing suitability', 'DW_TOTDWLG': 'Total- Occupied private dwellings by dwelling condition', 'DW_REGMIN': 'Only regular maintenance or minor repairs needed', 'DW_MAJORRE': 'Major repairs needed', 'DW_TOTDWL7': 'Total - Private households by number of household maintainers', 'DW_ACOST': 'Average monthly shelter costs for owned dwellings ($)', 'DW_AVALUE': 'Average value of dwelling $', 'ED_15NC': 'population aged 15 years and over: No certificate, diploma or degree', 'ED_15HSC': 'population aged 15 years and over: Secondary (high) school diploma or equivalency certificate', 'ED_15POS': 'population aged 15 years and over: Postsecondary certificate, diploma or degree', 'ED_15TRC': 'population aged 15 years and over: Apprenticeship or trades certificate or diploma', 'ED_15APP': 'population aged 15 years and over: Certificate of Apprenticeship or Certificate of Qualification', 'ED_15COL': 'population aged 15 years and over: College, CEGEP or other non-university certificate or diploma', 'ED_15UD_B': 'population aged 15 years and over: University certificate or diploma below bachelor level', 'ED_15UD': 'population aged 15 years and over: University certificate, diploma or degree at bachelor level or above', 'ED_15BD': "population aged 15 years and over: Bachelor's degree", 'ED_15BDPL': 'population aged 15 years and over: University certificate or diploma above bachelor level', 'ED_15MED': 'population aged 15 years and over: Degree in medicine, dentistry, veterinary medicine or optometry', 'ED_15MAS': "population aged 15 years and over: Master's degree", 'ED_15DOC': 'population aged 15 years and over: Earned doctorate', 'ED_24NC': 'No certificate, diploma or degree', 'ED_24HSC': 'Secondary (high) school diploma or equivalency certificate', 'ED_24POS': 'Postsecondary certificate, diploma or degree', 'ED_24TRC': 'Apprenticeship or trades certificate or diploma', 'ED_24APP': 'Certificate of Apprenticeship or Certificate of Qualification', 'ED_24COL': 'College, CEGEP or other non-university certificate or diploma', 'ED_24UD_B': 'University certificate or diploma below bachelor level', 'ED_24UD': 'University certificate, diploma or degree at bachelor level or above', 'ED_24BD': "Bachelor's degree", 'ED_24BDPL': 'University certificate or diploma above bachelor level', 'ED_24MED': 'Degree in medicine, dentistry, veterinary medicine or optometry', 'ED_24MAS': "Master's degree", 'ED_24DOC': 'Earned doctorate', 'ED_64NC': 'No certificate, diploma or degree', 'ED_64HSC': 'Secondary (high) school diploma or equivalency certificate', 'ED_64POS': 'Postsecondary certificate, diploma or degree', 'ED_64TRC': 'Apprenticeship or trades certificate or diploma', 'ED_64APP': 'Certificate of Apprenticeship or Certificate of Qualification', 'ED_64COL': 'College, CEGEP or other non-university certificate or diploma', 'ED_64UD_B': 'University certificate or diploma below bachelor level', 'ED_64UD': 'University certificate, diploma or degree at bachelor level or above', 'ED_64BD': "Bachelor's degree", 'ED_64BDPL': 'University certificate or diploma above bachelor level', 'ED_64MED': 'Degree in medicine, dentistry, veterinary medicine or optometry', 'ED_64MAS': "Master's degree", 'ED_64DOC': 'Earned doctorate', 'ED_65NC': 'No certificate, diploma or degree', 'ED_65HSC': 'Secondary (high) school diploma or equivalency certificate', 'ED_65POS': 'Postsecondary certificate, diploma or degree', 'ED_65TRC': 'Apprenticeship or trades certificate or diploma', 'ED_65APP': 'Certificate of Apprenticeship or Certificate of Qualification', 'ED_65COL': 'College, CEGEP or other non-university certificate or diploma', 'ED_65UD_B': 'University certificate or diploma below bachelor level', 'ED_65UD': 'University certificate, diploma or degree at bachelor level or above', 'ED_65BD': "Bachelor's degree", 'ED_65BDPL': 'University certificate or diploma above bachelor level', 'ED_65MED': 'Degree in medicine, dentistry, veterinary medicine or optometry', 'ED_65MAS': "Master's degree", 'ED_65DOC': 'Earned doctorate', 'ED_MJNPC': 'No postsecondary certificate, diploma or degree', 'ED_MJEDU': 'Education', 'ED_MJART': 'Visual and performing arts, and communications technologies', 'ED_MJHM': 'Humanities', 'ED_MJSSC': 'Social and behavioural sciences and law', 'ED_MJADM': 'Business, management and public administration', 'ED_MJPHY': 'Physical and life sciences and technologies', 'ED_MJMATH': 'Mathematics, computer and information sciences', 'ED_MJARC': 'Architecture, engineering, and related technologies', 'ED_MJAGR': 'Agriculture, natural resources and conservation', 'ED_MJHLH': 'Health and related fields', 'ED_MJPPT': 'Personal, protective and transportation services', 'ED_MJNEC': 'Other', 'ED_FMJNPC': 'No postsecondary certificate, diploma or degree', 'ED_FMJEDU': 'Education', 'ED_FMJART': 'Visual and performing arts, and communications technologies', 'ED_FMJHM': 'Humanities', 'ED_FMJSSC': 'Social and behavioural sciences and law', 'ED_FMJADM': 'Business, management and public administration', 'ED_FMJPHY': 'Physical and life sciences and technologies', 'ED_FMJMATH': 'Mathematics, computer and information sciences', 'ED_FMJARC': 'Architecture, engineering, and related technologies', 'ED_FMJAGR': 'Agriculture, natural resources and conservation', 'ED_FMJHLH': 'Health and related fields', 'ED_FMJPPT': 'Personal, protective and transportation services', 'ED_FMJNEC': 'Other', 'ED_MMJNPC': 'No postsecondary certificate, diploma or degree', 'ED_MMJEDU': 'Education', 'ED_MMJART': 'Visual and performing arts, and communications technologies', 'ED_MMJHM': 'Humanities', 'ED_MMJSSC': 'Social and behavioural sciences and law', 'ED_MMJADM': 'Business, management and public administration', 'ED_MMJPHY': 'Physical and life sciences and technologies', 'ED_MMJMATH': 'Mathematics, computer and information sciences', 'ED_MMJARC': 'Architecture, engineering, and related technologies', 'ED_MMJAGR': 'Agriculture, natural resources and conservation', 'ED_MMJHLH': 'Health and related fields', 'ED_MMJPPT': 'Personal, protective and transportation services', 'ED_MMJNEC': 'Other', 'ED_LOCNPC': 'No postsecondary certificate, diploma or degree', 'ED_LOCC': 'Postsecondary certificate, diploma or degree', 'ED_CANADA': 'Location of study inside Canada', 'ED_SAMEPR': 'Same as province or territory of residence', 'ED_OTPR': 'Different than province or territory of residence', 'ED_OUTCAN': 'Location of study outside Canada', 'ED_15HL': 'population aged 15 years and over', 'ED_15TRCON': 'population aged 15 years and over', 'ED_24HL': 'Total - Highest certificate, diploma or degree for the population aged 15 -24 years and over in private households', 'ED_24TRCON': 'Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification', 'ED_64HL': 'Total - Highest certificate, diploma or degree for the population aged 25 to 64 years in private households', 'ED_64TRCON': 'Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification', 'ED_65HL': 'Total - Highest certificate, diploma or degree for the population aged 65 years and over  in private households', 'ED_65TRCON': 'Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification', 'ED_MJ': 'Total - Major field of study - Classification of Instructional Programs (CIP) 2016 for the population aged 15 years and over in private households. It is collected for the highest certificate, diploma or degree above the high school or secondary school level', 'ED_FMJ': 'Total - Major field of study - Classification of Instructional Programs (CIP) 2016 for the population aged 15 years and over in private households - Female', 'ED_MMJ': 'Total - Major field of study - Classification of Instructional Programs (CIP) 2016 for the population aged 15 years and over in private households - Male', 'ED_15LOC': 'population aged 15 years and over', 'MN_VIS': 'Total visible minority population', 'MN_SASIAN': 'South Asian Population', 'MN_CHINESE': 'Chinese Population', 'MN_BLACK': 'Black Population', 'MN_FILIPIN': 'Filipino Population', 'MN_LAMER': 'Latin American Population', 'MN_ARAB_': 'Arab Population', 'MN_SEASIA_': 'Southeast Asian Population', 'MN_WASIAN': 'West Asian Population', 'MN_KOREAN': 'Korean Population', 'MN_JAPANE': 'Japanese Population', 'MN_TOT': 'Total - Visible minority for the population in private households.  Visible minorities are persons, other than Aboriginal peoples, who are non-Caucasian in race or non-white in colour.', 'MN_NIE': "Visible minority, n.i.e. Includes respondents who reported a write-in response classified as a visible minority such as 'Polynesian', 'Guyanese', 'Mauritian', etc. Population", 'MN_MULT': "Multiple visible minorities. Includes respondents who reported more than one visible minority group by checking two or more mark-in circles, e.g. 'Black' and 'South Asia

In [3]:
selected

{'DW': ['DW_TOT',
  'DW_SINGLE',
  'DW_APT5_',
  'DW_OT',
  'DW_SEMI',
  'DW_ROW',
  'DW_DUP',
  'DW_APT_5',
  'DW_OT_SING',
  'DW_MOVA',
  'DW_TOTDWL5',
  'DW_OWNED',
  'DW_RENTED',
  'DW_TOTDWL6',
  'DW_PTCON',
  'DW_NPTCON',
  'DW_TOTDWL4',
  'DW_BRM0',
  'DW_BRM1',
  'DW_BRM2',
  'DW_BRM3',
  'DW_BRM4_',
  'DW_TOTDWL2',
  'DW_CON_60',
  'DW_CON6180',
  'DW_CON8190',
  'DW_CON9100',
  'DW_CON0105',
  'DW_CON0610',
  'DW_CON1116',
  'DW_CON17_',
  'DW_TOTDWL8',
  'DW_MT_25',
  'DW_MT2534',
  'DW_MT3544',
  'DW_MT4554',
  'DW_MT5564',
  'DW_MT6574',
  'DW_MT7584',
  'DW_MT85_',
  'DW_MCOST',
  'DW_ACOST',
  'DW_MVALUE',
  'DW_AVALUE',
  'DW_MINVAL',
  'DW_MAXVAL',
  'DW_VALSTD'],
 'ED': ['ED_15HL',
  'ED_15NC',
  'ED_15HSC',
  'ED_15POS',
  'ED_15TRC',
  'ED_15TRCON',
  'ED_15APP',
  'ED_15COL',
  'ED_15UD_B',
  'ED_15UD',
  'ED_15BD',
  'ED_15BDPL',
  'ED_15MED',
  'ED_15MAS',
  'ED_15DOC',
  'ED_24HL',
  'ED_24NC',
  'ED_24HSC',
  'ED_24POS',
  'ED_24TRC',
  'ED_24TRCON',
  'ED_24APP',
  'ED_24COL',
  'ED_24UD_B',
  'ED_24UD',
  'ED_24BD',
  'ED_24BDPL',
  'ED_24MED',
  'ED_24MAS',
  'ED_24DOC',
  'ED_64HL',
  'ED_64NC',
  'ED_64HSC',
  'ED_64POS',
  'ED_64TRC',
  'ED_64TRCON',
  'ED_64APP',
  'ED_64COL',
  'ED_64UD_B',
  'ED_64UD',
  'ED_64BD',
  'ED_64BDPL',
  'ED_64MED',
  'ED_64MAS',
  'ED_64DOC',
  'ED_65HL',
  'ED_65NC',
  'ED_65HSC',
  'ED_65POS',
  'ED_65TRC',
  'ED_65TRCON',
  'ED_65APP',
  'ED_65COL',
  'ED_65UD_B',
  'ED_65UD',
  'ED_65BD',
  'ED_65BDPL',
  'ED_65MED',
  'ED_65MAS',
  'ED_65DOC'],
 'EM': ['EM_TOT',
  'EM_NA',
  'EM_ALL',
  'EM_PEM',
  'EM_PSM',
  'EM_PLTOT',
  'EM_PLHOM',
  'EM_PLOCA',
  'EM_PLNOF',
  'EM_PLU',
  'EM_TRTOT',
  'EM_TRCD',
  'EM_TRCP',
  'EM_TRPB',
  'EM_TRWK',
  'EM_TRBK',
  'EM_TROT',
  'EM_CMTOT',
  'EM_CM_15',
  'EM_CM15_29',
  'EM_CM30_44',
  'EM_CM45_59',
  'EM_CM60_',
  'EM_LGTOT',
  'EM_LGSIN',
  'EM_LGOFFIC',
  'EM_LGEN',
  'EM_LGFR',
  'EM_LGNOF',
  'EM_LGCRE',
  'EM_LGINU',
  'EM_LGGER',
  'EM_LGPUN',
  'EM_LGPOR',
  'EM_LGSP',
  'EM_LGKOR',
  'EM_LGCAN',
  'EM_LGMAN',
  'EM_LGCH',
  'EM_LGOT'],
 'ET1': ['ET_TOT_A',
  'ET_ABO',
  'ET_NOABO',
  'ET_TOT',
  'ET_ABOO',
  'ET_ONAO',
  'ET_EURO',
  'ET_CARO',
  'ET_LAMO',
  'ET_AFRO',
  'ET_ASIAO',
  'ET_OCEO'],
 'ET2': ['ET_TOT_A',
  'ET_ABO',
  'ET_NOABO',
  'ET_TOT',
  'ET_ABOO',
  'ET_ONAO',
  'ET_EURO',
  'ET_CARO',
  'ET_LAMO',
  'ET_AFRO',
  'ET_ASIAO',
  'ET_OCEO'],
 'FM': ['FM_2P', 'FM_3P', 'FM_4P', 'FM_5_P', 'FM_AVG_P'],
 'HH': ['HH_1P',
  'HH_2P',
  'HH_3P',
  'HH_4P',
  'HH_5P',
  'HH_NUMPINH',
  'HH_AVGPINH',
  'HH_ONEFMHH',
  'HH_CP_NC',
  'HH_CP_CH',
  'HH_OWN',
  'HH_RENT',
  'HH_MRENT',
  'HH_ARENT'],
 'HL1': ['HL_OFFICIA',
  'HL_ENGLISH',
  'HL_FRENCH',
  'HL_NOFFICI',
  'HL_ABOR',
  'HL_NABOR',
  'HL_MULTI',
  'HL_EF',
  'HL_ENO',
  'HL_FNO',
  'HL_EFNO'],
 'HL2': ['HL_OFFICIA',
  'HL_ENGLISH',
  'HL_FRENCH',
  'HL_NOFFICI',
  'HL_ABOR',
  'HL_NABOR',
  'HL_MULTI',
  'HL_EF',
  'HL_ENO',
  'HL_FNO',
  'HL_EFNO'],
 'IM': ['IM_CAN',
  'IM_OT',
  'IM_TOT',
  'IM_NIMM',
  'IM_CNTRY',
  'IM_NPRES',
  'IM_CNTRY2',
  'IM_AMERICA',
  'IM_SEURO',
  'IM_SAFRI',
  'IM_ASIA',
  'IM_SOCEAN',
  'IM_SRECENT',
  'IM_RSAMERI',
  'IM_RSEURO',
  'IM_RAFRI',
  'IM_RASIA',
  'IM_RSOCEAN',
  'IM_CAT',
  'IM_ECON',
  'IM_SPON',
  'IM_REFUGEE',
  'IM_OTHER'],
 'IN1': ['IN_THH',
  'IN_HH_5',
  'IN_HH0510',
  'IN_HH1015',
  'IN_HH1520',
  'IN_HH2025',
  'IN_HH2530',
  'IN_HH3035',
  'IN_HH3540',
  'IN_HH4045',
  'IN_HH4550',
  'IN_HH5060',
  'IN_HH6070',
  'IN_HH7080',
  'IN_HH8090',
  'IN_HH90100',
  'IN_HH100_',
  'IN_HH10125',
  'IN_HH12150',
  'IN_HH15200',
  'IN_HH200_',
  'IN_MHH',
  'IN_AHH'],
 'IN2': ['IN_THH',
  'IN_HH_5',
  'IN_HH0510',
  'IN_HH1015',
  'IN_HH1520',
  'IN_HH2025',
  'IN_HH2530',
  'IN_HH3035',
  'IN_HH3540',
  'IN_HH4045',
  'IN_HH4550',
  'IN_HH5060',
  'IN_HH6070',
  'IN_HH7080',
  'IN_HH8090',
  'IN_HH90100',
  'IN_HH100_',
  'IN_HH10125',
  'IN_HH12150',
  'IN_HH15200',
  'IN_HH200_',
  'IN_MHH',
  'IN_AHH'],
 'LF': ['LF_15P',
  'LF_15',
  'LF_15EMP',
  'LF_15UEM',
  'LF_15NOT',
  'LF_15PR',
  'LF_15ER',
  'LF_15UR',
  'LF_INTOT',
  'LF_INNA',
  'LF_INALL',
  'LF_INAG',
  'LF_INMI',
  'LF_INUT',
  'LF_INCON',
  'LF_INMAN',
  'LF_INWH',
  'LF_INRT',
  'LF_INTR',
  'LF_ININF',
  'LF_INFIN',
  'LF_INRS',
  'LF_INPRO',
  'LF_INMG',
  'LF_INADM',
  'LF_INEDU',
  'LF_INHEA',
  'LF_INART',
  'LF_INACC',
  'LF_INOTH',
  'LF_INPUB'],
 'MN': ['MN_TOT',
  'MN_VIS',
  'MN_SASIAN',
  'MN_CHINESE',
  'MN_BLACK',
  'MN_FILIPIN',
  'MN_LAMER',
  'MN_ARAB_',
  'MN_SEASIA_',
  'MN_WASIAN',
  'MN_KOREAN',
  'MN_JAPANE',
  'MN_NIE',
  'MN_MULT',
  'MN_OT'],
 'OC': ['OC_TOT',
  'OC_NA',
  'OC_ALL',
  'OC_MG',
  'OC_BS',
  'OC_SC',
  'OC_HL',
  'OC_SSC',
  'OC_ART',
  'OC_SAL',
  'OC_TR',
  'OC_UN',
  'OC_UNPMU'],
 'PP': ['PP_0_14',
  'PP_15_64',
  'PP_65_',
  'PP_85',
  'PP_PP_AVG',
  'PP_PP_MED',
  'PP_MR_CL',
  'PP_NMR',
  'PP_SEP',
  'PP_DIVORCE',
  'PP_WIDOW'],
 'RL': ['RL_TOT',
  'RL_BUD',
  'RL_CHRI',
  'RL_HIND',
  'RL_JEW',
  'RL_MUSL',
  'RL_SIKH',
  'RL_ABOR',
  'RL_OTRL',
  'RL_NON']}

In [25]:
s3=boto3.client('s3')
list=s3.list_objects(Bucket='myhomely')['Contents']

In [28]:
s3 = boto3.client('s3')
s3.download_file('myhomely', 'source_data/msd/ET1.csv', 'ET1.csv')

In [9]:
ETone = pd.read_csv('s3://{}/{}'.format('myhomely/source_data/msd', 'ET1.csv'))

In [10]:
ETone.shape

(799313, 170)

In [7]:
ETone['POSTCODE'].nunique()

799313

In [23]:
ETtwo = pd.read_csv('s3://{}/{}'.format('myhomely/source_data/msd', 'ET2.csv'))

In [24]:
ETtwo.shape

(799313, 145)

In [11]:
ETtwo['POSTCODE'].nunique()

799313

In [26]:
ETone.columns.tolist()

['POSTCODE',
 'ET_TOT_A',
 'ET_ABO',
 'ET_ABOS',
 'ET_NAS',
 'ET_METIS',
 'ET_INUIT',
 'ET_ABOM',
 'ET_ABOOT',
 'ET_NOABO',
 'ET_TOT_AB',
 'ET_TOT_RI',
 'ET_TOT_NR',
 'ET_TOT_AB2',
 'ET_ABAN',
 'ET_ABANS',
 'ET_INDAN',
 'ET_METISAN',
 'ET_INUITAN',
 'ET_ABOANM',
 'ET_INDMET',
 'ET_INDINUI',
 'ET_METINUI',
 'ET_INMETIN',
 'ET_MABAN',
 'ET_MABANS',
 'ET_MINDAN',
 'ET_MMETISA',
 'ET_MINUITA',
 'ET_MABOANM',
 'ET_MINDMET',
 'ET_MINDINU',
 'ET_MMETINU',
 'ET_MINMETI',
 'ET_NABAN',
 'ET_TOT',
 'ET_ABOO',
 'ET_NAIND',
 'ET_INU',
 'ET_MET',
 'ET_ONAO',
 'ET_ACA',
 'ET_AME',
 'ET_CAN',
 'ET_NEWB',
 'ET_NEWF',
 'ET_NOVA',
 'ET_ONTA',
 'ET_QUE',
 'ET_PROV',
 'ET_EURO',
 'ET_BRIO',
 'ET_CHAN',
 'ET_CORN',
 'ET_ENG',
 'ET_IRI',
 'ET_MANX',
 'ET_SCO',
 'ET_WEL',
 'ET_BRI',
 'ET_FREO',
 'ET_ALSA',
 'ET_BRET',
 'ET_CORSICA',
 'ET_FRE',
 'ET_WEUO',
 'ET_AUST',
 'ET_BAVARIA',
 'ET_BLG',
 'ET_DUT',
 'ET_FLEM',
 'ET_FRIS',
 'ET_GER',
 'ET_LUXE',
 'ET_SWI',
 'ET_WEU',
 'ET_NEUO',
 'ET_DAN',
 'ET_FIN',
 'ET_ICE',
 'ET_NORW',
 'ET_SWE',
 'ET_NEU',
 'ET_EEUO',
 'ET_BULG',
 'ET_BYEL',
 'ET_CZEC',
 'ET_CZSL',
 'ET_ESTO',
 'ET_HGN',
 'ET_LATV',
 'ET_LITH',
 'ET_MOLD',
 'ET_POL',
 'ET_ROM',
 'ET_RUS',
 'ET_SLO',
 'ET_UKR',
 'ET_EEU',
 'ET_SEUO',
 'ET_ALBA',
 'ET_BOSN',
 'ET_CATALAN',
 'ET_CROATIA',
 'ET_CYPR',
 'ET_GRE',
 'ET_ITA',
 'ET_KOSO',
 'ET_MACE',
 'ET_MALT',
 'ET_MONTE',
 'ET_PORT',
 'ET_SER',
 'ET_SICI',
 'ET_SLOV',
 'ET_SPA',
 'ET_YUG',
 'ET_SEU',
 'ET_OEUO',
 'ET_BASQ',
 'ET_JEW',
 'ET_GYPS',
 'ET_SLAV',
 'ET_EUR',
 'ET_CARO',
 'ET_ANTI',
 'ET_BAHA',
 'ET_BARB',
 'ET_BERM',
 'ET_CARIB',
 'ET_CUBA',
 'ET_DOMI',
 'ET_GREN',
 'ET_GUADELO',
 'ET_HAI',
 'ET_JAMA',
 'ET_KITT',
 'ET_MART',
 'ET_MONT',
 'ET_PUER',
 'ET_STLU',
 'ET_TRI',
 'ET_VINC',
 'ET_WIN',
 'ET_CARI',
 'ET_LAMO',
 'ET_AFCS',
 'ET_ARAWAK',
 'ET_ARGE',
 'ET_BELI',
 'ET_BOLI',
 'ET_BRAZ',
 'ET_CHIL',
 'ET_COLO',
 'ET_COST',
 'ET_ECUA',
 'ET_GUAT',
 'ET_GUY',
 'ET_HISP',
 'ET_HOND',
 'ET_MAYA',
 'ET_MEXI',
 'ET_NICA',
 'ET_PANA',
 'ET_PARA',
 'ET_PERU',
 'ET_SALV',
 'ET_URUG',
 'ET_VENE',
 'ET_LAM']

In [33]:
ETone[['POSTCODE','ET_TOT_A']]

       POSTCODE  ET_TOT_A
0        A0A0B7     2.021
1        A0A0C2     2.010
2        A0A1A0    71.259
3        A0A1B0   596.075
4        A0A1C0  1552.877
...         ...       ...
799308   Y1A6W1    93.390
799309   Y1A7A1  1108.486
799310   Y1A7A2   663.928
799311   Y1A7A3    39.894
799312   Y1A7A4   247.632

[799313 rows x 2 columns]

In [27]:
ETtwo.columns.tolist()

['POSTCODE',
 'ET_AFRO',
 'ET_CWAFRO',
 'ET_AKAN',
 'ET_ANGO',
 'ET_ASHA',
 'ET_BENI',
 'ET_BURK',
 'ET_CAME',
 'ET_CHAD',
 'ET_CONGOL',
 'ET_EDO',
 'ET_EWE',
 'ET_GABO',
 'ET_GAMB',
 'ET_GHAN',
 'ET_GUIN',
 'ET_IBO',
 'ET_IVOR',
 'ET_LIBE',
 'ET_MALI',
 'ET_MALINKE',
 'ET_NIGE',
 'ET_PEUL',
 'ET_SENE',
 'ET_SIER',
 'ET_TOGO',
 'ET_WOLOF',
 'ET_YORU',
 'ET_CWAFR',
 'ET_NAFRO',
 'ET_ALGE',
 'ET_BERB',
 'ET_COPT',
 'ET_DINK',
 'ET_EGY',
 'ET_LEB',
 'ET_MAURE',
 'ET_MORO',
 'ET_SUDA',
 'ET_TUNI',
 'ET_NAFR',
 'ET_SEAFRO',
 'ET_AFRI',
 'ET_AMHA',
 'ET_BANT',
 'ET_BURU',
 'ET_DJIBOUT',
 'ET_ERIT',
 'ET_ETHI',
 'ET_HARA',
 'ET_KENY',
 'ET_MALA',
 'ET_MAUR',
 'ET_OROM',
 'ET_RWAN',
 'ET_SEYC',
 'ET_SOMA',
 'ET_SOUT',
 'ET_TANZ',
 'ET_TIGR',
 'ET_UGAN',
 'ET_ZAMB',
 'ET_ZIMB',
 'ET_ZULU',
 'ET_SEAFR',
 'ET_OAFRO',
 'ET_BLK',
 'ET_AFR',
 'ET_ASIAO',
 'ET_WASIAO',
 'ET_AFGH',
 'ET_ARB',
 'ET_ARM',
 'ET_ASSY',
 'ET_AZER',
 'ET_GEOR',
 'ET_HAZARA',
 'ET_IRA',
 'ET_IRAQ',
 'ET_ISRA',
 'ET_JORD',
 'ET_KAZA',
 'ET_KURD',
 'ET_KUWA',
 'ET_KYRGYZ',
 'ET_LEBA',
 'ET_PALE',
 'ET_PASH',
 'ET_SAUD',
 'ET_SYRI',
 'ET_TAJI',
 'ET_TATA',
 'ET_TURK',
 'ET_TURKMEN',
 'ET_UIGH',
 'ET_UZBE',
 'ET_YEME',
 'ET_WASIA',
 'ET_SA',
 'ET_BANG',
 'ET_BENG',
 'ET_BHUTANE',
 'ET_EIN',
 'ET_GOAN',
 'ET_GUJA',
 'ET_KASH',
 'ET_NEPA',
 'ET_PAK',
 'ET_PUN',
 'ET_SINH',
 'ET_SLK',
 'ET_TAMI',
 'ET_SAS',
 'ET_ESAO',
 'ET_BURM',
 'ET_CAMBK',
 'ET_CHIN',
 'ET_FIL',
 'ET_HMON',
 'ET_INDO',
 'ET_JAP',
 'ET_KAREN',
 'ET_KOR',
 'ET_LAOT',
 'ET_MALAY',
 'ET_MONG',
 'ET_SING',
 'ET_TAIW',
 'ET_THAI',
 'ET_TIBE',
 'ET_VTN',
 'ET_ESAS',
 'ET_OASIAO',
 'ET_ASIA',
 'ET_OCEO',
 'ET_AUS',
 'ET_NEW',
 'ET_PACO',
 'ET_FIJI',
 'ET_HAWA',
 'ET_MAOR',
 'ET_POLY',
 'ET_SAMO',
 'ET_PACI']

In [13]:
set(ETone['POSTCODE'].unique()) - set(ETtwo['POSTCODE'].unique())

set()

In [15]:
postalcodes = set(ETone['POSTCODE'].unique())

In [22]:
for key in selected.keys():
    try:
        print(key)
        print(pd.read_csv('s3://{}/{}'.format('myhomely/source_data/msd', key + '.csv'))['POSTCODE'].nunique())
        gc.collect()
        gc.collect()
    except:
        print("except")
        print(key)

DW
ED
799313
EM
ET1
799313
ET2
799313
FM
799313
HH
799313
HL1
799313
HL2
799313
IM
IN1
799313
IN2
799313
LF
MN
799313
OC
PP
799313
RL
799313

In [30]:
for key in selected.keys():
    try:
        print(key)
        print(postalcodes - set(pd.read_csv('s3://{}/{}'.format('myhomely/source_data/msd', key + '.csv'))['POSTCODE'].unique()))
        gc.collect()
        gc.collect()
    except:
        continue

DW
ED
set()
EM
ET1
set()
ET2
set()
FM
set()
HH
set()
HL1
set()
HL2
set()
IM
IN1
set()
IN2
set()
LF
MN
set()
OC
PP
set()
RL
set()

In [31]:
for key in ['DW','EM','IM','LF','OC']:
    print(key)
    print(pd.read_csv('s3://{}/{}'.format('myhomely/source_data/msd', key + '.csv')).columns.tolist()[:2])

DW
['postcode', 'DW_TOT']
EM
['PostCode', 'EM_TOT']
IM
['PostCode', 'IM_TOT2']
LF
['PostCode', 'LF_15P']
OC
['PostCode', 'OC_TOT']

In [58]:
# for key in selected.keys():
for key in selected.keys():
    print(key)
    df = pd.read_csv('s3://{}/{}'.format('myhomely/source_data/msd', key + '.csv'))
    gc.collect()
    gc.collect()
    if 'POSTCODE' in df.columns.tolist():
        columns = [x for x in selected[key] if x in df.columns.tolist()]
        print(columns)
        df = df[['POSTCODE']+columns]
        df.to_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', key + '.csv'))
    if 'PostCode' in df.columns.tolist():
        columns = [x for x in selected[key] if x in df.columns.tolist()]
        print(columns)
        df = df[['PostCode']+columns]
        df = df.rename(columns = {'PostCode' : 'POSTCODE'})
        df.to_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', key + '.csv'))
    if 'postcode' in df.columns.tolist():
        columns = [x for x in selected[key] if x in df.columns.tolist()]
        print(columns)
        df = df[['postcode']+columns]
        df = df.rename(columns = {'postcode' : 'POSTCODE'})
        df.to_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', key + '.csv'))

DW
['DW_TOT', 'DW_SINGLE', 'DW_APT5_', 'DW_OT', 'DW_SEMI', 'DW_ROW', 'DW_DUP', 'DW_APT_5', 'DW_OT_SING', 'DW_MOVA', 'DW_TOTDWL5', 'DW_OWNED', 'DW_RENTED', 'DW_TOTDWL6', 'DW_PTCON', 'DW_NPTCON', 'DW_TOTDWL4', 'DW_BRM0', 'DW_BRM1', 'DW_BRM2', 'DW_BRM3', 'DW_BRM4_', 'DW_TOTDWL2', 'DW_CON_60', 'DW_CON6180', 'DW_CON8190', 'DW_CON9100', 'DW_CON0105', 'DW_CON0610', 'DW_CON1116', 'DW_CON17_', 'DW_TOTDWL8', 'DW_MT_25', 'DW_MT2534', 'DW_MT3544', 'DW_MT4554', 'DW_MT5564', 'DW_MT6574', 'DW_MT7584', 'DW_MT85_', 'DW_MCOST', 'DW_ACOST', 'DW_MVALUE', 'DW_AVALUE', 'DW_MINVAL', 'DW_MAXVAL', 'DW_VALSTD']
ED
['ED_15HL', 'ED_15NC', 'ED_15HSC', 'ED_15POS', 'ED_15TRC', 'ED_15TRCON', 'ED_15APP', 'ED_15COL', 'ED_15UD_B', 'ED_15UD', 'ED_15BD', 'ED_15BDPL', 'ED_15MED', 'ED_15MAS', 'ED_15DOC', 'ED_24HL', 'ED_24NC', 'ED_24HSC', 'ED_24POS', 'ED_24TRC', 'ED_24TRCON', 'ED_24APP', 'ED_24COL', 'ED_24UD_B', 'ED_24UD', 'ED_24BD', 'ED_24BDPL', 'ED_24MED', 'ED_24MAS', 'ED_24DOC', 'ED_64HL', 'ED_64NC', 'ED_64HSC', 'ED_64POS', 'ED_64TRC', 'ED_64TRCON', 'ED_64APP', 'ED_64COL', 'ED_64UD_B', 'ED_64UD', 'ED_64BD', 'ED_64BDPL', 'ED_64MED', 'ED_64MAS', 'ED_64DOC', 'ED_65HL', 'ED_65NC', 'ED_65HSC', 'ED_65POS', 'ED_65TRC', 'ED_65TRCON', 'ED_65APP', 'ED_65COL', 'ED_65UD_B', 'ED_65UD', 'ED_65BD', 'ED_65BDPL', 'ED_65MED', 'ED_65MAS', 'ED_65DOC']
EM
['EM_TOT', 'EM_NA', 'EM_ALL', 'EM_PEM', 'EM_PSM', 'EM_PLTOT', 'EM_PLHOM', 'EM_PLOCA', 'EM_PLNOF', 'EM_PLU', 'EM_TRTOT', 'EM_TRCD', 'EM_TRCP', 'EM_TRPB', 'EM_TRWK', 'EM_TRBK', 'EM_TROT', 'EM_CMTOT', 'EM_CM_15', 'EM_CM15_29', 'EM_CM30_44', 'EM_CM45_59', 'EM_CM60_', 'EM_LGTOT', 'EM_LGSIN', 'EM_LGOFFIC', 'EM_LGEN', 'EM_LGFR', 'EM_LGNOF', 'EM_LGCRE', 'EM_LGINU', 'EM_LGGER', 'EM_LGPUN', 'EM_LGPOR', 'EM_LGSP', 'EM_LGKOR', 'EM_LGCAN', 'EM_LGMAN', 'EM_LGCH', 'EM_LGOT']
ET1
['ET_TOT_A', 'ET_ABO', 'ET_NOABO', 'ET_TOT', 'ET_ABOO', 'ET_ONAO', 'ET_EURO', 'ET_CARO', 'ET_LAMO']
ET2
['ET_AFRO', 'ET_ASIAO', 'ET_OCEO']
FM
['FM_2P', 'FM_3P', 'FM_4P', 'FM_5_P', 'FM_AVG_P']
HH
['HH_1P', 'HH_2P', 'HH_3P', 'HH_4P', 'HH_5P', 'HH_NUMPINH', 'HH_AVGPINH', 'HH_ONEFMHH', 'HH_CP_NC', 'HH_CP_CH', 'HH_OWN', 'HH_RENT', 'HH_MRENT', 'HH_ARENT']
HL1
['HL_OFFICIA', 'HL_ENGLISH', 'HL_FRENCH', 'HL_NOFFICI', 'HL_ABOR', 'HL_NABOR']
HL2
['HL_MULTI', 'HL_EF', 'HL_ENO', 'HL_FNO', 'HL_EFNO']
IM
['IM_CAN', 'IM_OT', 'IM_TOT', 'IM_NIMM', 'IM_CNTRY', 'IM_NPRES', 'IM_CNTRY2', 'IM_AMERICA', 'IM_SEURO', 'IM_SAFRI', 'IM_ASIA', 'IM_SOCEAN', 'IM_SRECENT', 'IM_RSAMERI', 'IM_RSEURO', 'IM_RAFRI', 'IM_RASIA', 'IM_RSOCEAN', 'IM_CAT', 'IM_ECON', 'IM_SPON', 'IM_REFUGEE', 'IM_OTHER']
IN1
[]
IN2
['IN_THH', 'IN_HH_5', 'IN_HH0510', 'IN_HH1015', 'IN_HH1520', 'IN_HH2025', 'IN_HH2530', 'IN_HH3035', 'IN_HH3540', 'IN_HH4045', 'IN_HH4550', 'IN_HH5060', 'IN_HH6070', 'IN_HH7080', 'IN_HH8090', 'IN_HH90100', 'IN_HH100_', 'IN_HH10125', 'IN_HH12150', 'IN_HH15200', 'IN_HH200_', 'IN_MHH', 'IN_AHH']
LF
['LF_15P', 'LF_15', 'LF_15EMP', 'LF_15UEM', 'LF_15NOT', 'LF_15PR', 'LF_15ER', 'LF_15UR', 'LF_INTOT', 'LF_INNA', 'LF_INALL', 'LF_INAG', 'LF_INMI', 'LF_INUT', 'LF_INCON', 'LF_INMAN', 'LF_INWH', 'LF_INRT', 'LF_INTR', 'LF_ININF', 'LF_INFIN', 'LF_INRS', 'LF_INPRO', 'LF_INMG', 'LF_INADM', 'LF_INEDU', 'LF_INHEA', 'LF_INART', 'LF_INACC', 'LF_INOTH', 'LF_INPUB']
MN
['MN_TOT', 'MN_VIS', 'MN_SASIAN', 'MN_CHINESE', 'MN_BLACK', 'MN_FILIPIN', 'MN_LAMER', 'MN_ARAB_', 'MN_SEASIA_', 'MN_WASIAN', 'MN_KOREAN', 'MN_JAPANE', 'MN_NIE', 'MN_MULT', 'MN_OT']
OC
['OC_TOT', 'OC_NA', 'OC_ALL', 'OC_MG', 'OC_BS', 'OC_SC', 'OC_HL', 'OC_SSC', 'OC_ART', 'OC_SAL', 'OC_TR', 'OC_UN', 'OC_UNPMU']
PP
['PP_0_14', 'PP_15_64', 'PP_65_', 'PP_85', 'PP_PP_AVG', 'PP_PP_MED', 'PP_MR_CL', 'PP_NMR', 'PP_SEP', 'PP_DIVORCE', 'PP_WIDOW']
RL
['RL_TOT', 'RL_BUD', 'RL_CHRI', 'RL_HIND', 'RL_JEW', 'RL_MUSL', 'RL_SIKH', 'RL_ABOR', 'RL_OTRL', 'RL_NON']

In [59]:
selected.keys()

dict_keys(['DW', 'ED', 'EM', 'ET1', 'ET2', 'FM', 'HH', 'HL1', 'HL2', 'IM', 'IN1', 'IN2', 'LF', 'MN', 'OC', 'PP', 'RL'])

In [ ]:
# ETone[['POSTCODE'] + selected['ET1']]

In [40]:
df1 = pd.read_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', 'ED' + '.csv'))

In [52]:
pd.testing.assert_frame_equal(df1,df)

KeyboardInterrupt:

In [45]:
df1 = df1.drop(columns ='Unnamed: 0' )

In [46]:
df1.columns

Index(['POSTCODE', 'ED_15HL', 'ED_15NC', 'ED_15HSC', 'ED_15POS', 'ED_15TRC',
       'ED_15TRCON', 'ED_15APP', 'ED_15COL', 'ED_15UD_B', 'ED_15UD', 'ED_15BD',
       'ED_15BDPL', 'ED_15MED', 'ED_15MAS', 'ED_15DOC', 'ED_24HL', 'ED_24NC',
       'ED_24HSC', 'ED_24POS', 'ED_24TRC', 'ED_24TRCON', 'ED_24APP',
       'ED_24COL', 'ED_24UD_B', 'ED_24UD', 'ED_24BD', 'ED_24BDPL', 'ED_24MED',
       'ED_24MAS', 'ED_24DOC', 'ED_64HL', 'ED_64NC', 'ED_64HSC', 'ED_64POS',
       'ED_64TRC', 'ED_64TRCON', 'ED_64APP', 'ED_64COL', 'ED_64UD_B',
       'ED_64UD', 'ED_64BD', 'ED_64BDPL', 'ED_64MED', 'ED_64MAS', 'ED_64DOC',
       'ED_65HL', 'ED_65NC', 'ED_65HSC', 'ED_65POS', 'ED_65TRC', 'ED_65TRCON',
       'ED_65APP', 'ED_65COL', 'ED_65UD_B', 'ED_65UD', 'ED_65BD', 'ED_65BDPL',
       'ED_65MED', 'ED_65MAS', 'ED_65DOC'],
      dtype='object')

In [48]:
df1.head()

,POSTCODE,ED_15HL,ED_15NC,ED_15HSC,ED_15POS,ED_15TRC,ED_15TRCON,ED_15APP,ED_15COL,ED_15UD_B,...,ED_65TRCON,ED_65APP,ED_65COL,ED_65UD_B,ED_65UD,ED_65BD,ED_65BDPL,ED_65MED,ED_65MAS,ED_65DOC
0,A0A0B7,1.761,0.602,0.417,0.742,0.212,0.076,0.136,0.452,0.000,...,0.076,0.030,0.121,0.000,0.006,0.006,0.000,0.000,0.000,0.000
1,A0A0C2,1.796,0.541,0.590,0.665,0.243,0.171,0.072,0.199,0.077,...,0.040,0.014,0.032,0.018,0.008,0.000,0.000,0.000,0.008,0.000
2,A0A1A0,66.984,19.035,23.970,23.979,6.273,4.362,1.910,14.682,1.241,...,1.614,0.839,7.302,0.416,0.884,0.387,0.005,0.002,0.483,0.002
3,A0A1B0,514.819,62.453,77.717,374.648,146.537,25.261,121.276,135.810,20.335,...,4.055,24.080,9.249,14.893,20.611,15.248,0.000,0.000,5.363,0.000
4,A0A1C0,1282.586,280.903,315.726,685.957,149.907,68.083,81.824,289.645,31.140,...,13.585,17.941,26.086,5.346,39.320,19.878,5.733,0.000,13.709,0.000

In [49]:
df.head()

,POSTCODE,ED_15HL,ED_15NC,ED_15HSC,ED_15POS,ED_15TRC,ED_15TRCON,ED_15APP,ED_15COL,ED_15UD_B,...,ED_65TRCON,ED_65APP,ED_65COL,ED_65UD_B,ED_65UD,ED_65BD,ED_65BDPL,ED_65MED,ED_65MAS,ED_65DOC
0,A0A0B7,1.761,0.602,0.417,0.742,0.212,0.076,0.136,0.452,0.000,...,0.076,0.030,0.121,0.000,0.006,0.006,0.000,0.000,0.000,0.000
1,A0A0C2,1.796,0.541,0.590,0.665,0.243,0.171,0.072,0.199,0.077,...,0.040,0.014,0.032,0.018,0.008,0.000,0.000,0.000,0.008,0.000
2,A0A1A0,66.984,19.035,23.970,23.979,6.273,4.362,1.910,14.682,1.241,...,1.614,0.839,7.302,0.416,0.884,0.387,0.005,0.002,0.483,0.002
3,A0A1B0,514.819,62.453,77.717,374.648,146.537,25.261,121.276,135.810,20.335,...,4.055,24.080,9.249,14.893,20.611,15.248,0.000,0.000,5.363,0.000
4,A0A1C0,1282.586,280.903,315.726,685.957,149.907,68.083,81.824,289.645,31.140,...,13.585,17.941,26.086,5.346,39.320,19.878,5.733,0.000,13.709,0.000

Join all the tables

In [26]:
# for key in selected.keys():
for key in ['DW']:
    print(key)
    flatfile = pd.read_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', key + '.csv')).drop(columns = ['Unnamed: 0'])

DW

In [27]:
selected.keys()

dict_keys(['DW', 'ED', 'EM', 'ET1', 'ET2', 'FM', 'HH', 'HL1', 'HL2', 'IM', 'IN1', 'IN2', 'LF', 'MN', 'OC', 'PP', 'RL'])

In [28]:
# for key in selected.keys():
for key in selected.keys():
    if key != 'DW':
        print(key)
        gc.collect()
        gc.collect()
        df = pd.read_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', key + '.csv')).drop(columns = ['Unnamed: 0'])
        flatfile = flatfile.merge(df,how = 'left',on ='POSTCODE')

ED
EM
ET1
ET2
FM
HH
HL1
HL2
IM
IN1
IN2
LF
MN
OC
PP
RL

In [29]:
flatfile.shape

(799313, 316)

In [11]:
col = []
for key in selected.keys():
    col = col + selected[key]

In [14]:
len(set(col)), len(col)

(315, 361)

In [16]:
valuecounts(col)

NameError: name 'valuecounts' is not defined

In [39]:
# for key in selected.keys():
for key in selected.keys():
    print(key)
    df = pd.read_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', key + '.csv')).drop(columns = ['Unnamed: 0'])
    gc.collect()
    gc.collect()
    print(set(selected[key]) - set(df.columns.tolist()))

DW
set()
ED
set()
EM
set()
ET1
{'ET_ASIAO', 'ET_AFRO', 'ET_OCEO'}
ET2
{'ET_NOABO', 'ET_EURO', 'ET_ONAO', 'ET_TOT', 'ET_CARO', 'ET_ABO', 'ET_ABOO', 'ET_TOT_A', 'ET_LAMO'}
FM
set()
HH
set()
HL1
{'HL_FNO', 'HL_EFNO', 'HL_MULTI', 'HL_EF', 'HL_ENO'}
HL2
{'HL_NOFFICI', 'HL_ENGLISH', 'HL_FRENCH', 'HL_NABOR', 'HL_OFFICIA', 'HL_ABOR'}
IM
set()
IN1
{'IN_HH90100', 'IN_HH1520', 'IN_HH100_', 'IN_HH12150', 'IN_HH8090', 'IN_HH3035', 'IN_HH4550', 'IN_HH10125', 'IN_HH2025', 'IN_HH1015', 'IN_HH15200', 'IN_HH2530', 'IN_HH4045', 'IN_HH_5', 'IN_HH200_', 'IN_HH3540', 'IN_THH', 'IN_HH6070', 'IN_HH5060', 'IN_MHH', 'IN_HH7080', 'IN_HH0510', 'IN_AHH'}
IN2
set()
LF
set()
MN
set()
OC
set()
PP
set()
RL
set()

In [4]:
df = pd.read_csv('s3://{}/{}'.format('myhomely/source_data/msd', 'ET1' + '.csv'))

In [5]:
df2 = pd.read_csv('s3://{}/{}'.format('myhomely/source_data/msd', 'ET2' + '.csv'))

In [9]:
'ET_NOABO' in df.columns

True

In [8]:
'ET_ASIAO' in df2.columns

True

In [38]:
flatfile.to_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', 'flatfile' + '.csv'))

In [40]:
flatfile

,POSTCODE,DW_TOT,DW_SINGLE,DW_APT5_,DW_OT,DW_SEMI,DW_ROW,DW_DUP,DW_APT_5,DW_OT_SING,...,RL_TOT,RL_BUD,RL_CHRI,RL_HIND,RL_JEW,RL_MUSL,RL_SIKH,RL_ABOR,RL_OTRL,RL_NON
0,A0A0B7,0.951,0.951,0.0,0.000,0.000,0.000,0.000,0.0,0.000,...,2.021,0.000,2.021,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,A0A0C2,0.955,0.955,0.0,0.000,0.000,0.000,0.000,0.0,0.000,...,2.010,0.000,2.010,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,A0A1A0,39.918,39.680,0.0,0.238,0.068,0.099,0.071,0.0,0.000,...,71.259,0.000,69.543,0.000,0.000,0.000,0.000,0.003,0.000,1.713
3,A0A1B0,290.713,275.630,0.0,15.083,0.000,9.980,5.102,0.0,0.000,...,596.075,0.000,596.075,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,A0A1C0,559.119,539.041,0.0,20.077,3.529,16.133,0.416,0.0,0.000,...,1552.877,2.062,1406.895,3.991,0.921,8.739,0.592,0.000,2.579,127.099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799308,Y1A6W1,29.548,22.102,0.0,7.446,5.548,0.000,1.898,0.0,0.000,...,93.390,0.687,51.982,0.454,0.039,0.074,0.088,0.000,1.024,39.042
799309,Y1A7A1,480.552,218.703,0.0,261.848,205.825,43.995,12.028,0.0,0.000,...,1108.486,13.145,398.483,4.718,0.601,2.805,2.528,0.003,0.005,686.198
799310,Y1A7A2,287.826,166.894,0.0,117.702,98.458,15.127,3.205,0.0,0.911,...,663.928,3.482,275.013,1.168,0.243,0.848,0.635,0.003,0.006,382.530
799311,Y1A7A3,17.295,7.871,0.0,9.424,7.408,1.583,0.433,0.0,0.000,...,39.894,0.473,14.341,0.170,0.022,0.101,0.091,0.000,0.000,24.696
799312,Y1A7A4,107.353,63.157,0.0,44.197,37.259,5.724,1.213,0.0,0.000,...,247.632,1.299,102.574,0.436,0.091,0.316,0.237,0.001,0.002,142.676

In [25]:
flatfile = pd.read_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', 'flatfile' + '.csv')).drop(columns = ['Unnamed: 0'])

In [26]:
dictionaryselected = {}

In [27]:
for key in datadictionary.keys():
    if key in flatfile.columns.tolist():
        dictionaryselected[key] = datadictionary[key]

In [28]:
len(dictionaryselected.keys())

315

In [29]:
flatfile.rename(columns=dictionaryselected, inplace = True)

In [30]:
flatfile

,POSTCODE,Total - Occupied private dwellings by structural type of dwelling,Single-detached house,"Apartment, building that has five or more storeys",Other attached dwelling,Semi-detached house,Row house,"Apartment, detached duplex","Apartment, building that has fewer than five storeys",Other single-attached house,...,Total population in private households by religion,Buddhist,Christian,Hindu,Jewish,Muslim,Sikh,Traditional (Aboriginal) Spirituality,Other religions,No religious affiliation
0,A0A0B7,0.951,0.951,0.0,0.000,0.000,0.000,0.000,0.0,0.000,...,2.021,0.000,2.021,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,A0A0C2,0.955,0.955,0.0,0.000,0.000,0.000,0.000,0.0,0.000,...,2.010,0.000,2.010,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,A0A1A0,39.918,39.680,0.0,0.238,0.068,0.099,0.071,0.0,0.000,...,71.259,0.000,69.543,0.000,0.000,0.000,0.000,0.003,0.000,1.713
3,A0A1B0,290.713,275.630,0.0,15.083,0.000,9.980,5.102,0.0,0.000,...,596.075,0.000,596.075,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,A0A1C0,559.119,539.041,0.0,20.077,3.529,16.133,0.416,0.0,0.000,...,1552.877,2.062,1406.895,3.991,0.921,8.739,0.592,0.000,2.579,127.099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799308,Y1A6W1,29.548,22.102,0.0,7.446,5.548,0.000,1.898,0.0,0.000,...,93.390,0.687,51.982,0.454,0.039,0.074,0.088,0.000,1.024,39.042
799309,Y1A7A1,480.552,218.703,0.0,261.848,205.825,43.995,12.028,0.0,0.000,...,1108.486,13.145,398.483,4.718,0.601,2.805,2.528,0.003,0.005,686.198
799310,Y1A7A2,287.826,166.894,0.0,117.702,98.458,15.127,3.205,0.0,0.911,...,663.928,3.482,275.013,1.168,0.243,0.848,0.635,0.003,0.006,382.530
799311,Y1A7A3,17.295,7.871,0.0,9.424,7.408,1.583,0.433,0.0,0.000,...,39.894,0.473,14.341,0.170,0.022,0.101,0.091,0.000,0.000,24.696
799312,Y1A7A4,107.353,63.157,0.0,44.197,37.259,5.724,1.213,0.0,0.000,...,247.632,1.299,102.574,0.436,0.091,0.316,0.237,0.001,0.002,142.676

In [31]:
flatfile = flatfile.round(4)

In [32]:
flatfile

,POSTCODE,Total - Occupied private dwellings by structural type of dwelling,Single-detached house,"Apartment, building that has five or more storeys",Other attached dwelling,Semi-detached house,Row house,"Apartment, detached duplex","Apartment, building that has fewer than five storeys",Other single-attached house,...,Total population in private households by religion,Buddhist,Christian,Hindu,Jewish,Muslim,Sikh,Traditional (Aboriginal) Spirituality,Other religions,No religious affiliation
0,A0A0B7,0.951,0.951,0.0,0.000,0.000,0.000,0.000,0.0,0.000,...,2.021,0.000,2.021,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,A0A0C2,0.955,0.955,0.0,0.000,0.000,0.000,0.000,0.0,0.000,...,2.010,0.000,2.010,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,A0A1A0,39.918,39.680,0.0,0.238,0.068,0.099,0.071,0.0,0.000,...,71.259,0.000,69.543,0.000,0.000,0.000,0.000,0.003,0.000,1.713
3,A0A1B0,290.713,275.630,0.0,15.083,0.000,9.980,5.102,0.0,0.000,...,596.075,0.000,596.075,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,A0A1C0,559.119,539.041,0.0,20.077,3.529,16.133,0.416,0.0,0.000,...,1552.877,2.062,1406.895,3.991,0.921,8.739,0.592,0.000,2.579,127.099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799308,Y1A6W1,29.548,22.102,0.0,7.446,5.548,0.000,1.898,0.0,0.000,...,93.390,0.687,51.982,0.454,0.039,0.074,0.088,0.000,1.024,39.042
799309,Y1A7A1,480.552,218.703,0.0,261.848,205.825,43.995,12.028,0.0,0.000,...,1108.486,13.145,398.483,4.718,0.601,2.805,2.528,0.003,0.005,686.198
799310,Y1A7A2,287.826,166.894,0.0,117.702,98.458,15.127,3.205,0.0,0.911,...,663.928,3.482,275.013,1.168,0.243,0.848,0.635,0.003,0.006,382.530
799311,Y1A7A3,17.295,7.871,0.0,9.424,7.408,1.583,0.433,0.0,0.000,...,39.894,0.473,14.341,0.170,0.022,0.101,0.091,0.000,0.000,24.696
799312,Y1A7A4,107.353,63.157,0.0,44.197,37.259,5.724,1.213,0.0,0.000,...,247.632,1.299,102.574,0.436,0.091,0.316,0.237,0.001,0.002,142.676

In [33]:
flatfile.to_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', 'flatfile-readable-keys' + '.csv'))

In [34]:
flatfilemini = flatfile.iloc[0:1000,:]

In [35]:
flatfilemini.to_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', 'flatfilemini' + '.csv'))

In [36]:
flatfilemini = pd.read_csv('s3://{}/{}'.format('myhomely/raja/Manifold-selected', 'flatfilemini' + '.csv')).drop(columns = ['Unnamed: 0'])

In [37]:
flatfilemini

,POSTCODE,Total - Occupied private dwellings by structural type of dwelling,Single-detached house,"Apartment, building that has five or more storeys",Other attached dwelling,Semi-detached house,Row house,"Apartment, detached duplex","Apartment, building that has fewer than five storeys",Other single-attached house,...,Total population in private households by religion,Buddhist,Christian,Hindu,Jewish,Muslim,Sikh,Traditional (Aboriginal) Spirituality,Other religions,No religious affiliation
0,A0A0B7,0.951,0.951,0.000,0.000,0.000,0.000,0.000,0.000,0.0,...,2.021,0.000,2.021,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,A0A0C2,0.955,0.955,0.000,0.000,0.000,0.000,0.000,0.000,0.0,...,2.010,0.000,2.010,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,A0A1A0,39.918,39.680,0.000,0.238,0.068,0.099,0.071,0.000,0.0,...,71.259,0.000,69.543,0.000,0.000,0.000,0.000,0.003,0.000,1.713
3,A0A1B0,290.713,275.630,0.000,15.083,0.000,9.980,5.102,0.000,0.0,...,596.075,0.000,596.075,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,A0A1C0,559.119,539.041,0.000,20.077,3.529,16.133,0.416,0.000,0.0,...,1552.877,2.062,1406.895,3.991,0.921,8.739,0.592,0.000,2.579,127.099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A1A4B4,12.841,8.149,0.000,4.693,0.000,0.000,4.693,0.000,0.0,...,33.225,0.001,28.485,0.014,0.007,0.001,0.001,0.000,0.001,4.715
996,A1A4B5,15.066,11.299,0.000,3.766,0.000,0.000,3.766,0.000,0.0,...,36.854,0.001,32.984,0.768,0.000,0.002,0.001,0.000,0.001,3.097
997,A1A4B6,5.040,3.361,0.000,1.679,0.000,0.000,1.679,0.000,0.0,...,11.336,0.000,9.361,0.000,0.370,0.738,0.000,0.000,0.001,0.865
998,A1A4B7,47.364,0.000,25.454,21.909,0.000,0.000,0.000,21.909,0.0,...,115.681,0.000,111.588,0.000,0.001,0.000,0.003,0.000,0.004,4.084
999,A1A4B8,198.519,0.000,0.000,198.519,0.000,0.000,0.000,198.519,0.0,...,441.508,18.564,359.546,0.337,0.003,3.908,0.208,0.000,0.000,58.942

In [41]:
x = flatfile.isna().sum()

In [46]:
flatfile['Standard deviation (dispersion) of dwelling values in the postal code'].isna().sum()

2